### ISSUE TITLE
Failed CSRF check!

### ISSUE THREAD

**Issue by zbiki** [adrianfalleiro/slim-cli-runner#15]
hi, I have a problem in my local development environment the call in the console works fine, when I load everything into the live environment and start the console call I get a "Failed CSRF check!", what could be the problem?

command:
/usr/bin/php -f /var/www/html/mak/public/index.php SampleTask listen

local php:
PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

live php:
PHP 7.3.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 28 2019 07:37:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

mfg
Christian

**Comment by adrianfalleiro** [comment]
@zbiki Do you have an example project?

**Comment by zbiki** [comment]
sorry for my late reply, I restarted the server and now it works like magic.
Many thanks for the great tasks :)
mfg
Christian
