### ISSUE TITLE
Error psr7 version in composer require

### ISSUE THREAD

**Issue by ramik5** [adrianfalleiro/slim-cli-runner#19]
Hello! I use "slim/psr7": "^1.0" in my project. In composer require i get next error:

Problem 1
    - Installation request for adrianfalleiro/slim-cli-runner ^3.0 -> satisfiable by adrianfalleiro/slim-cli-runner[3.0].
    - adrianfalleiro/slim-cli-runner 3.0 requires slim/psr7 ^0.6.0 -> satisfiable by slim/psr7[0.6] but these conflict with your requirements or minimum-stability.

How resolve this problem with use "slim/psr7": "^1.0"?

**Comment by adrianfalleiro** [comment]
Fixed in `adrianfalleiro/slim-cli-runner@3.1`
